server:
  port: 8888
  context-path: /
   
helloWorld: Hello EveryBody
   
msyql:
   jdbcName: com.mysql.jdbc.Driver
   dbUrl: jdbc:mysql://localhost:3306/db_diary
   userName: root
   password: 123456
 
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_book
      username: root
      password: 123456
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
